# Generated by Django 5.2.7 on 2025-11-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='Untitled Campaign', help_text="Campaign name (e.g., 'Summer Sale', 'Wedding 2024')", max_length=100),
        ),
    ]
