# Generated by Django 5.2.7 on 2025-11-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='frame_flip_h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='frame_flip_v',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='frame_opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='frame_rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='frame_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='output_size',
            field=models.CharField(default='instagram_post', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='frame_image',
            field=models.ImageField(blank=True, null=True, upload_to='frames/'),
        ),
        migrations.CreateModel(
            name='CampaignFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_image', models.ImageField(upload_to='frames/')),
                ('name', models.CharField(default='Frame', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='campaigns.campaignframe'),
        ),
    ]
