# Generated by Django 5.2.7 on 2025-11-14 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_generatedimage_frame_flip_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='frame_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='campaignframe',
            name='frame_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='generated_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='user_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
