# Generated by Django 5.2.7 on 2025-11-15 02:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_frame_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedimage',
            old_name='user_photo',
            new_name='poster_image',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='frame_flip_h',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='frame_flip_v',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='frame_opacity',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='frame_rotation',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='frame_scale',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='profile_position',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='output_size',
            field=models.CharField(default='square_1080', max_length=50),
        ),
    ]
