# Generated by Django 5.2.7 on 2025-11-15 02:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_rename_user_photo_generatedimage_poster_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='poster_image',
        ),
        migrations.CreateModel(
            name='CampaignPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(default='Poster', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_images', to='campaigns.campaignposter'),
        ),
    ]
